### ISSUE TITLE
How to set `$TMPDIR` environment variable with a job to something like `<scratch>/$SLURM_JOB_ID/tmp`

### ISSUE THREAD

**Issue by hermidalc** [snakemake/snakemake-executor-plugin-slurm#119]
Using the executor plugin how do I set the `$TMPDIR` env var (and therefore `tmpdir` resource) within a job to something like `<scratch>/$SLURM_JOB_ID/tmp`?

**Comment by hermidalc** [comment]
https://github.com/snakemake/snakemake/issues/2423

**Comment by cmeesters** [comment]
that is something your admins ought to do. Yet, the [fs-plugin](https://snakemake.github.io/snakemake-plugin-catalog/plugins/storage/fs.html) should do, what you are looking for. [Alas, a bug is buggin us.](https://github.com/snakemake/snakemake-storage-plugin-fs/issues/19) I hope, this will be fixed soon.
