### ISSUE TITLE
Jobid is not properly parsed when cluster name is present

### ISSUE THREAD

**Issue by nigiord** [snakemake/snakemake-executor-plugin-slurm#121]
>   snakemake-executor-plugin-slurm=0.8.0
>   snakemake-executor-plugin-slurm-jobstep=0.2.1

Currently the executor-plugin parses the job id of the submitted jobs by taking the last word of the output from the sbatch command:

https://github.com/snakemake/snakemake-executor-plugin-slurm/blob/6a5ed46d6b4d692863ce981e6fff81915c0bd2fc/snakemake_executor_plugin_slurm/__init__.py#L194-L203

It fails on the cluster I use because for some reason the output looks like this:
> Submitted batch job 3969755 on cluster nautilus

Hence, the executor-plugin thinks that all my job ids are equal to `nautilus`. It raises multiple issues, including the fact that the scheduler cannot resume after jobs are completed.

I’m not sure why the message on my cluster is different from the one expected, I think it’s the default behaviour of slurm when a cluster name is defined (we have multiple clusters defined). My slurm version is:

`sinfo --version`
> slurm 22.05.7-Atos.1.1

In any case, the current parsing does not seem very robust as this output message could be altered in future versions of slurm. A temporary workaround on my side is to replace `slurm_jobid = out.split(" ")[-1]`by `slurm_jobid = out.split(" ")[-4] ` but that’s rather hideous. In recent versions of slurm, sbatch as the `--parsable` option that only returns jobid and clustername, semicolon separated:

https://slurm.schedmd.com/sbatch.html

> --parsable
>     Outputs only the job id number and the cluster name if present. The values are separated by a semicolon. Errors will still be displayed. 

Would it be possible to include this option directly in the sbatch call? And then to split by semicolon the result to get the job id (it should not failed, even if the cluster is not defined).

**Comment by nigiord** [comment]
Apparently the `--parsable` option was added on slurm version 14.03 https://gitlab.com/SchedMD/slurm/-/blob/master/NEWS#L11206-11207 , i.e. roughtly 10 years ago. I think it’s safe to assume we can rely on it.

**Comment by nigiord** [comment]
I submitted a PR that fixes the issue.

https://github.com/snakemake/snakemake-executor-plugin-slurm/pull/122

**Comment by cmeesters** [comment]
Hi,

sorry, there was a PR for a while (#56 ) fixing multicluster submission (issue #53). We discussed for a while on how to implement a test for this in the CI. Then stuff happened. I now merged the mentioned PR and it will be automatically released for bioconda and pyi.

Please test version 0.9 once ready.

**Comment by nigiord** [comment]
Hi @cmeesters, thank you for the update. I can confirm the bug I mentioned is gone on 0.9.0.

I just have doubts regarding the way the sbatch output is now parsed:

https://github.com/snakemake/snakemake-executor-plugin-slurm/blob/03d474f74f703c4e4530bbeda8f16dcf43764263/snakemake_executor_plugin_slurm/__init__.py#L207-L211

As mentioned in the comment, this might change in future versions of Slurm. I think using `--parsable` would be more robust (it just returns `JOBID;CLUSTERNAME` and is less likely to change in future slurm updates).

Cheers,
Nils

**Comment by cmeesters** [comment]
I'll put it on my todo.
