### ISSUE TITLE
Getting an AttributeError: module 'pulp' has no attribute 'list_solvers'. Did you mean: 'listSolvers'?

### ISSUE THREAD

**Issue by Pooshman** [snakemake/snakemake-executor-plugin-slurm#150]
snakemake 8.20.3

After activating snakemake, when trying to run snakemake --version, I get the following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/snakemake", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/snakemake/__init__.py", line 2631, in main
    parser = get_argument_parser()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/snakemake/__init__.py", line 1545, in get_argument_parser
    lp_solvers = pulp.list_solvers(onlyAvailable=True)
AttributeError: module 'pulp' has no attribute 'list_solvers'. Did you mean: 'listSolvers'?

```
I used the following 6 commands to download Miniconda:
<img width="722" alt="Screenshot 2024-09-18 at 10 58 55 AM" src="https://github.com/user-attachments/assets/2874ab82-50bb-4345-85df-0775506183ed">

I then ran the following 3 commands
<img width="727" alt="Screenshot 2024-09-18 at 11 00 23 AM" src="https://github.com/user-attachments/assets/1459b618-b48b-4957-bf8f-5c5fbcb28bd3">

After that I ran snakemake --version and got the error. Any help would be appreciated, thanks!

**Comment by cmeesters** [comment]
I am not sure, where this originated. But it certainly has nothing to do with this plugin repository: pulp is no dependency of the plugin, and the traceback you get is from Snakemake's core.

However, when installing a conda derivative it is unusual, to create a directory beforehand. My suggestion would be to remove your installation and follow the instructions [from the Snakemake documentation](https://snakemake.readthedocs.io/en/stable/getting_started/installation.html), closely. If the issue persists, please refer to the Snakemake main repo, not a plugin you are not using.
