### ISSUE TITLE
slurm job name could be more informative

### ISSUE THREAD

**Issue by dgordon562** [snakemake/snakemake-executor-plugin-slurm#154]
Per Johannes' suggestion, I am submitting this:

 job grouping is great!  E.g.,
snakemake   --groups blast_on_fugu_file=blastg --group-components blastg=16 

However, I am finding that all of my slurm that are all named like:
wgac-GROUP-batch=10
so I can't tell which rule (which job group) is currently running.   Is there a way to get the slurm jobs named by the name of the job group or the name of the rule (in the case in which the job group has a single rule)?

Thanks!
David

**Comment by dgordon562** [comment]
Per Johannes, please assign this request to Christian Meesters and Johannes.

**Comment by dgordon562** [comment]
Thanks, Christian!  Anything you can do would be appreciated.  Right now what I have to do is to parse the log file to see which rule it is using.  That a pain in the a**.

**Comment by johanneskoester** [comment]
Note that the Snakemake output also lists the slurm log for each job or group when submitting and upon error.

**Comment by johanneskoester** [comment]
This should solve the issue: https://github.com/snakemake/snakemake/pull/3168

**Comment by dgordon562** [comment]
thank you so much, Johannes!
Do you have a page somewhere with instructions for how to get these new
features?  The
instructions would need to assume many of us don't know much about git
(except "git clone").
Such instructions would be good for everyone who is interested in getting
any new feature.
Maybe you already have such instructions somewhere...

Thanks again!
Best wishes,
David

**Comment by dgordon562** [comment]
Thank you, Christian.

Another stupid question:  to see if there is a new snakemake release, do I
go to:
https://github.com/snakemake/snakemake
and check here (see snapshot below)?   So whenever that version changes,
this new feature will
be in it and then I can get it via bioconda?

[image: image.png]

**Comment by johanneskoester** [comment]
It takes some 1-3 hours for the release to appear on bioconda. If you want to be sure whether a new release is already in bioconda, check here: https://anaconda.org/bioconda/snakemake/files

**Comment by dgordon562** [comment]
thanks, Johannes!
(and, of course, thanks for all your years of work on this very useful
product)
