### ISSUE TITLE
support for slurm job arrays?

### ISSUE THREAD

**Issue by andrewkern** [snakemake/snakemake-executor-plugin-slurm#158]
I'm wondering if this plugin currently has support for slurm job arrays? this is related to #115

**Comment by cmeesters** [comment]
it's on my to-do list

**Comment by andrewkern** [comment]
fair enough! i'll look forward to it

**Comment by nickp60** [comment]
@cmeesters could you use some help with this?  We just switched from lsf to slurm so I'm no slurm expert but I'd be happy to discuss if there would be a way I could contribute
