### ISSUE TITLE
checkpointing jobs

### ISSUE THREAD

**Issue by j-bac** [snakemake/snakemake-executor-plugin-slurm#179]
**Is your feature request related to a problem? Please describe.**
Slurm clusters often have a time limit on jobs

**Describe the solution you'd like**
A way to checkpoint long jobs and resume them to bypass time limit

**Comment by cmeesters** [comment]
There was a plan to do support checkpointing via SLURM. I am not aware that it has ever been successfully / reliably implemented. Please correct my if I am wrong.

If an application does support checkpointing, you can define a checkpoint file as a (temporary) output and a further resume job with that output as input (plus putatively more).  I confess: To do this as generic as possible might be tricky.

Either way: If this is related to this plugin, I would need a more detailed description. Note that the plugin can deal with pre-emption and resuming jobs, already.

**Comment by j-bac** [comment]
I am talking about checkpointing and resuming a single script (that does not do checkpointing by itself).

This was possible for snakemake 7 by modifying the submit_job function (see e.g., the snakemake section here [https://wiki.unil.ch/ci/books/high-performance-computing-hpc/page/checkpoint-slurm-jobs-IW2](https://wiki.unil.ch/ci/books/high-performance-computing-hpc/page/checkpoint-slurm-jobs-IW2))

Maybe there is a way to do something similar by modifying run_job ? [https://github.com/snakemake/snakemake-executor-plugin-slurm/blob/531ebc672fec4c579c701add9d29d178125644e6/snakemake_executor_plugin_slurm/__init__.py#L110](https://github.com/snakemake/snakemake-executor-plugin-slurm/blob/531ebc672fec4c579c701add9d29d178125644e6/snakemake_executor_plugin_slurm/__init__.py#L110)

**Comment by cmeesters** [comment]
That link refers to a (cluster specific?) file in Lausanne, which in turn refers to CRIU. We can hardly introduce dependencies which are not likely to find on _every_ cluster using SLURM. Also, the SLURM profile was using an actual jobscript (a shellscript - it was a dummy, but still a physical script). In avoiding I/O overhead for _every_ submission we (I) opted to use the wrapper function from `sbatch`.

But, I admit, this is all idle speculation. Is the source code for this  `ckpt_methods.sh` script available?

**Comment by cmeesters** [comment]
@j-bac Thank you for sharing the script with me. You see, around line 50, there is a statement like `sudo <path>/bin/wrapper ...`. This means that any such feature would need root privilege, something we cannot take for granted, and that there is a cluster-specific binary, which is not available elsewhere.

To port such a feature is not easy. [DMTCP](https://dmtcp.sourceforge.io/), for instance

- makes distinctions between MPI and smp applications necessary
- might need special paths on the command line
- will take memory overhead

To make such things work _everywhere_ is pretty futile. I would welcome a some hints for a more generic software which does not require additional privileges.
