### ISSUE TITLE
srun: error: slurm_init_msg_engine_port error Address already in use

### ISSUE THREAD

**Issue by y9c** [snakemake/snakemake-executor-plugin-slurm#24]
This error occurs by chance. 

snakemake version 8.2.0
 
```
srun: error: slurm_init_msg_engine_port error Address already in use
```

**Comment by cmeesters** [comment]
I apologize for being so late with my reply. This

> This error occurs by chance.

is not really helpful, as I am sure you are aware of. Please update to the latest release and indicate the command you have been using. Perhaps a minimal input to generate the error, too (if you can get hold of the issue, that is)? It would be splendid!

I know, it is at times difficult to provoke a bug, which does not show itself consistently.

**Comment by y9c** [comment]
Thank you for your suggestion. I am not sure what triggered this bug and it is hard to reproduce. I will update this issue when I have more clue about this.

**Comment by cmeesters** [comment]
Please update to the most current versions of Snakemake and this plugin. I will close this issue, now. Feel free to open it, when such an error occurs again.
