### ISSUE TITLE
Directory separator in wildcards not handled in updated logfile names

### ISSUE THREAD

**Issue by jaicher** [snakemake/snakemake-executor-plugin-slurm#47]
#35 adds wildcards to logfile name. As mentioned in https://github.com/snakemake/snakemake-executor-plugin-slurm/pull/35#issuecomment-1977523028, if the wildcards include the dimension separator "/", the parent directory of the resulting logfile cannot be created prior to submitting to slurm/is done incorrectly, so these jobs immediately fail.

**Comment by cmeesters** [comment]
Thanks for being patient: I was on a conference.

Can you please provide an example? I'm trying to figure out, whether your issue stems from the character itself, or the path separator (os.path.sep` on Linux). Eventually, the code should be as robust as possible (even though SLURM will not run under windows).

**Comment by jaicher** [comment]
Hi @cmeesters thanks for being patient as well; I was out traveling. The issue comes from the path separator, not the character itself. When the path separator is present in `wildcard_str`, it makes `os.path.dirname(slurm_logfile)` include `%j`, so `os.makedirs(...)` cannot make the appropriate directory for the slurm logfile. I pushed a modification replacing "/" with `os.path.sep` to my PR. Thank you for recognizing the OS-specific logic and helping me improve the PR!

**Comment by cmeesters** [comment]
Ought to be fixed with merger of PR#67, be sure to have version >= 0.4.4 .
