### ISSUE TITLE
Snakemake 8 not usable with Slurm clusters offering GPUs

### ISSUE THREAD

**Issue by w8jcik** [snakemake/snakemake-executor-plugin-slurm#52]
As previously reported
- https://github.com/snakemake/snakemake/issues/2701
- https://github.com/snakemake/snakemake-executor-plugin-slurm/issues/18

Snakemake 8.9 still fails to submit jobs to a Slurm cluster when requesting GPU resources.

`profiles/default/config.yaml`

```yaml
executor: slurm

default-resources:
  ...
  slurm_extra: "'--gres=gpu:1'"
```

```
Select jobs to execute...
InputFunctionException in rule [obfuscated] in file [obfuscated]/Snakefile, line 6:
Error:
  WorkflowError:
    Failed to evaluate resources value '--gres=gpu:1'.
        String arguments may need additional quoting. E.g.: --default-resources "tmpdir='/home/user/tmp'" or --set-resources "somerule:someresource='--nice=100'". This also holds for setting resources inside of a profile, where you might have to enclose them in single and double quotes, i.e. someresource: "'--nice=100'".
    SyntaxError: invalid syntax (<string>, line 1)
```

## Versions

- Freshly installed Conda https://docs.anaconda.com/free/miniconda/#quick-command-line-install
- Snakemake installed with Mamba as described here https://snakemake.readthedocs.io/en/stable/getting_started/installation.html
- Snakemake 8.9
- `snakemake-executor-plugin-slurm@0.4.2`
- Python 3.12
- Slurm 23.11.4

**Comment by cmeesters** [comment]
I'm afraid I could reproduce this issue.

We are working on a fix - actually this has been fixed, should be covered by a test case and still, it reoccurred. My apologies.

**Comment by cmeesters** [comment]
Thank you for your patience - I was absent and could not test. 

Please update to the latest version of Snakemake: The parsing is now stable.
