### ISSUE TITLE
The benchmark directive does not work when slurm is used as the executor

### ISSUE THREAD

**Issue by stefmldk** [snakemake/snakemake-executor-plugin-slurm#55]
Dear developers
The benchmark directive, that may be added to a rule, works fine with the default executor. But if slurm is used as the executor (via snakemake-executor-plugin-slurm), it seems that no benchmark files get created. Snakemake version: 8.10.0.

Thank you for all your hard work!

Cheers!

**Comment by cmeesters** [comment]
Hm, that would affect my next steps directly. I will investigate this early next week (currently, I am on a retreat).

**Comment by stefmldk** [comment]
Update: It appears that the benchmark directive DOES WORK with slurm. The reason it appeared as if it didn't was that I had used a wrong account that did not have the expected compute resources associated. It was able to complete some jobs, but apparently extracting benchmarking info was prohibited. Changing the account to one with the expected compute resources made the benchmarking info appear. I apologize, but still this is quite illustrative.
Thanks.

**Comment by cmeesters** [comment]
Thank you for the feedback - I was about to ask for additional information today as the feature works for us just like intended.
