### ISSUE TITLE
Constraints that include logical "or" cause Snakemake to hang

### ISSUE THREAD

**Issue by w8jcik** [snakemake/snakemake-executor-plugin-slurm#58]
Constraints are used to select GPU types, architectures and CPU types.

Using [logical _or_](https://slurm.schedmd.com/sbatch.html#OPT_OR) leads to Snakemake neither failing or submitting a job.

Example profile `profiles/default/config.yaml`

```yaml
executor: slurm

default-resources:
  ...
  constraint: "turing|ampere"
```

# Observations

- Both `turing` and `ampere` work when used separately.
- Specifying non existent constraint leads to failure which is fine.

```
WorkflowError:
SLURM job submission failed. The error message was sbatch: error: Batch job submission failed: Invalid feature specification
```

- Using _or_ operator leads to neither failure or submission. It just keeps hanging.

My first guess is that this parameter is passed directly to shell and then `|` results in opening a pipe.

**Comment by cmeesters** [comment]
I'm afraid, your assumption is correct. I will attempt a fix today. Meanwhile, you could try: `constraint: "'turing|ampere'"`.

**Comment by w8jcik** [comment]
> Meanwhile, you could try: constraint: "'turing|ampere'".

I tried with quotes and without, the outcome is the same.

**Comment by cmeesters** [comment]
We do not have a test case, yet. That might take a little while, yet you can try the code in PR #64 . Just clone, switch to branch `fix/#58_logical_constraints` and (assuming you are working with a conda/mamba environment, use `poetry install` from your cloned directory.

I hope, we have the fix tested in a few days.

**Comment by w8jcik** [comment]
I successfully queued some jobs to the cluster using `|` operator, so I believe that the change works.

Thank you for help.
