### ISSUE TITLE
Slurm executor plugin is not found after installation

### ISSUE THREAD

**Issue by vsbuffalo** [snakemake/snakemake-executor-plugin-slurm#77]
Hi,

I am having trouble getting even a simple MRE to work. I also have not found any examples or installation instructions to get this plugin to work, so I'm hoping you can help me.

`requirements.txt`:
```
snakemake>=8
snakemake-executor-plugin-cluster-generic
```

```
$ pip install --requirement requirements.txt
```

```
$ snakemake --executor slurm
[...]
snakemake: error: argument --executor/-e: invalid choice: 'slurm' (choose from 'cluster-generic', 'local', 'dryrun', 'touch')
```

I have not found any instructions in the Snakemake docs on how to register a plugin, and assume such an action is unneeded. Is there something wrong with this MRE? 

Note that this has not worked on a linux cluster, nor my OS X machine.

Thanks,
Vince

**Comment by cmeesters** [comment]
The plugin is called `snakemake-executor-slurm` and will install its dependency `snakemake-executor-slurm-jobstep`. Neither `snakemake` nor `snakemake-executor-plugin-cluster-generic` will install this plugin. The latter is not even designed for a SLURM batch system. 

Regarding pip, may a quote the docs?

> Instead of conda, snakemake can be installed with pip. However, note that snakemake has non-python dependencies, such that the pip based installation has a limited functionality if those dependencies are not manually installed in addition.

BTW — Dependency resolution works regardless of the operating system you are working on.

**Comment by vsbuffalo** [comment]
My apologies for this error (perhaps I shouldn't have created this issue so late at night).

But the error was in my issue, not in my steps I think. I had tried manually installing `snakemake-executor-plugin-slurm` too with pip. (Note: above you say `snakemake-executor-slurm` — did you mean `snakemake-executor-plugin-slurm` which is what [the documentation here](https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html) says? When I try `pip install snakemake-executor-slurm` it says it does not exist.)

The correct `requirements.txt` is:

```
snakemake>=8
snakemake-executor-plugin-slurm
```

but even with this, and `pip install --requirement requirements.txt` and `snakemake --executor slurm` it still can't find it: 

```
$ snakemake --executor slurm
[...]
snakemake: error: argument --executor/-e: invalid choice: 'slurm' (choose from 'cluster-generic', 'local', 'dryrun', 'touch')
```

Apologies if I am missing something obvious here.

**Comment by vsbuffalo** [comment]
Hm, so I did get this working on my linux cluster (I am not sure how). Either way, I am happy to close the issue. Thank you.
