### ISSUE TITLE
All SLURM jobs created by snakemake have the same name

### ISSUE THREAD

**Issue by xapple** [snakemake/snakemake-executor-plugin-slurm#83]
It seems like the SLURM job names are simply assigned with UUIDs here:

https://github.com/snakemake/snakemake-executor-plugin-slurm/blob/912df8380b00742d256f42db8e7ab20d3836715b/snakemake_executor_plugin_slurm/__init__.py#L52

However in my testing, I would end up with all the jobs launched in my snakemake pipeline having the same name.

![uuid](https://github.com/snakemake/snakemake-executor-plugin-slurm/assets/649288/2ef8f5a6-91c3-4fb2-86a4-17585beda1f1)

Any ideas why that could be ?

**Comment by cmeesters** [comment]
> Any ideas why that could be ?

[Yes](https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html#inquiring-about-job-information-and-adjusting-the-rate-limiter).

**Comment by cmeesters** [comment]
As we state: The plugin queries the job status of all jobs of a workflow using this name, which is unique per workflow. Hence, the ability to query with the comment, which is the rule name per job.
