### ISSUE TITLE
Wildcards missing from comments

### ISSUE THREAD

**Issue by mrvollger** [snakemake/snakemake-executor-plugin-slurm#85]
Hello, 

I was very excited to see in the [patch notes](https://github.com/snakemake/snakemake-executor-plugin-slurm/blob/main/CHANGELOG.md#features) the inclusion of wildcards in the slurm comment and log path.  

So I updated the plugin to get those features, and while I see wildcards in the log path (e.g. `.snakemake/slurm_logs/rule_fire/PS00474_HG02630_1_JAHAOQ010000001.1/18033650.log`), I still don't see them in the SLURM comment field, just the rule name (e.g. `fire`). Any ideas?

Thanks in advance,
Mitchell

**Comment by cmeesters** [comment]
Hello Mitchell,

yes, indeed. We could do that. At first I was a bit hesitant - not knowing what the buffer size for SLURM strings is. And I bloody well do not want to break anybodies batch system. Yet, SLURM matured over time and as far as I can tell (please, anyone correct me, if I am wrong!), there is no such string limit for comments of job names. And my own tinkering with hello world scripts confirms this.

So, I will - as time permits - draft a PR.

Cheers
Christian

**Comment by mrvollger** [comment]
Great! Made a small PR ^. Hope it helps.

**Comment by mrvollger** [comment]
closed in #88.

**Comment by cmeesters** [comment]
Ah, you are faster than me - got pretty busy.

Anyway, this issues does not go without a "Thank you!".
